spring:
  application:
    name: query-api

  datasource:
    url: jdbc:postgresql://localhost:5432/f1_telemetry
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081