spring:
  application:
    name: telemetry-processor

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: telemetry-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  datasource:
    url: jdbc:postgresql://localhost:5432/f1_telemetry
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
